/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import yumxpress.dao.CompanyDao;
import yumxpress.dao.ProductDao;
import yumxpress.pojo.ProductPojo;
import yumxpress.util.UserDetails;

/**
 *
 * @author Swadesh Sharma
 */
public class OrderFoodFrame extends javax.swing.JFrame {

    /**
     * Creates new form OrderFoodFrame
     */
    private Map<String,String> companyMap;
    private List<ProductPojo> productList;
    static List<ProductPojo> orderProductList=new ArrayList<>();
    private int listIndex;
    private JFrame showFrame;
    public OrderFoodFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.custName.setText(UserDetails.getCustName());
        loadCompanyNames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        custName = new javax.swing.JLabel();
        btnMyAcc = new javax.swing.JButton();
        btnMyCart = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        btnOderHistory = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        frame = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        companyNameList = new javax.swing.JComboBox<>();
        backClick = new javax.swing.JLabel();
        nextClick = new javax.swing.JLabel();
        food2 = new javax.swing.JLabel();
        food3 = new javax.swing.JLabel();
        food4 = new javax.swing.JLabel();
        food5 = new javax.swing.JLabel();
        food1 = new javax.swing.JLabel();
        food6 = new javax.swing.JLabel();
        foodName3 = new javax.swing.JLabel();
        foodName2 = new javax.swing.JLabel();
        foodName5 = new javax.swing.JLabel();
        foodName1 = new javax.swing.JLabel();
        foodName6 = new javax.swing.JLabel();
        foodName4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 198, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/user.png"))); // NOI18N

        custName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        custName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custName.setText("jLabel4");

        btnMyAcc.setBackground(new java.awt.Color(255, 173, 84));
        btnMyAcc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnMyAcc.setText("My Account");
        btnMyAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyAccActionPerformed(evt);
            }
        });

        btnMyCart.setBackground(new java.awt.Color(255, 173, 84));
        btnMyCart.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnMyCart.setText("My Cart");
        btnMyCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyCartActionPerformed(evt);
            }
        });

        btnCancelOrder.setBackground(new java.awt.Color(255, 173, 84));
        btnCancelOrder.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCancelOrder.setText("Cancel Order");

        btnOderHistory.setBackground(new java.awt.Color(255, 173, 84));
        btnOderHistory.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnOderHistory.setText("Order History");
        btnOderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOderHistoryActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 173, 84));
        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel3))
                            .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMyCart, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMyAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnMyAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnMyCart, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnOderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frame.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 198, 255));
        jLabel2.setText("Order Food");

        companyNameList.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        companyNameList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameListActionPerformed(evt);
            }
        });

        backClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icons8-left-arrow-64.png"))); // NOI18N
        backClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backClickMouseClicked(evt);
            }
        });

        nextClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icons8-right-arrow-64.png"))); // NOI18N
        nextClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextClickMouseClicked(evt);
            }
        });

        food2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        food2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderFoodFrame.this.mouseClicked(evt);
            }
        });

        food3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        food3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderFoodFrame.this.mouseClicked(evt);
            }
        });

        food4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        food4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderFoodFrame.this.mouseClicked(evt);
            }
        });

        food5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        food5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderFoodFrame.this.mouseClicked(evt);
            }
        });

        food1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        food1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderFoodFrame.this.mouseClicked(evt);
            }
        });

        food6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        food6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderFoodFrame.this.mouseClicked(evt);
            }
        });

        foodName3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        foodName3.setForeground(new java.awt.Color(255, 173, 84));
        foodName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        foodName2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        foodName2.setForeground(new java.awt.Color(255, 173, 84));
        foodName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        foodName5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        foodName5.setForeground(new java.awt.Color(255, 173, 84));
        foodName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        foodName1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        foodName1.setForeground(new java.awt.Color(255, 173, 84));
        foodName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        foodName6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        foodName6.setForeground(new java.awt.Color(255, 173, 84));
        foodName6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        foodName4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        foodName4.setForeground(new java.awt.Color(255, 173, 84));
        foodName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame);
        frame.setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLayout.createSequentialGroup()
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(companyNameList, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(backClick)
                        .addGap(44, 44, 44)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameLayout.createSequentialGroup()
                                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(food1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foodName1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(food2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foodName2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(frameLayout.createSequentialGroup()
                                        .addComponent(food3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(foodName3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(frameLayout.createSequentialGroup()
                                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(food4, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(foodName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(food5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(foodName5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(food6, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(foodName6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(46, 46, 46)
                        .addComponent(nextClick)))
                .addGap(43, 43, 43))
            .addGroup(frameLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(companyNameList, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(food1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(food2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(food3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foodName1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(foodName3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(foodName2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(food4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(food5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(food6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(backClick)
                    .addComponent(nextClick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodName5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodName6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodName4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyAccActionPerformed
        CustomerAccountFrame caf=new CustomerAccountFrame();
        caf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyAccActionPerformed

    private void btnOderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOderHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOderHistoryActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        CustomerLoginFrame clf= new CustomerLoginFrame();
        clf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void backClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backClickMouseClicked
//        if(listIndex<productList.size()){
//            showDetails();
//        }
//        else{
//            listIndex=0;
//            showDetails();
//        }
    }//GEN-LAST:event_backClickMouseClicked

    private void nextClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextClickMouseClicked
        if(listIndex<productList.size()){
            showDetails();
        }
        else{
            listIndex=0;
            showDetails();
        }
    }//GEN-LAST:event_nextClickMouseClicked

    private void companyNameListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameListActionPerformed
        String compName=this.companyNameList.getSelectedItem().toString();
        String compId=companyMap.get(compName);
        if(compId==null){
            compId="All";
        }
        try{
            productList=ProductDao.getAllProductsByCompanyId(compId);
            showDetails();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "DB Error in CustomerRegisterFrame");
            ex.printStackTrace();
        }catch(IOException ex){
            JOptionPane.showMessageDialog(null, "Image Error in CustomerRegisterFrame");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_companyNameListActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        JLabel lbl=(JLabel)evt.getSource();
        int index=Integer.parseInt(lbl.getName());
        if(index>=productList.size()){
            JOptionPane.showMessageDialog(null, "Invalid Item Clicked");
            return;
        }
        String []str={"Add to Cart","Buy Now"};
        int choice=JOptionPane.showOptionDialog(null, "What do you want to do ?", "Select", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, str, str[1]);
        if(choice==0){
            ProductPojo p=productList.get(index);
            orderProductList.add(p);
        }
        else{
            ProductPojo p=productList.get(index);
            showFrame=new OrderProductFrame(p);
            showFrame.setVisible(true);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_mouseClicked

    private void btnMyCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyCartActionPerformed
        new CustomerCartFrame().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnMyCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFoodFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backClick;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyAcc;
    private javax.swing.JButton btnMyCart;
    private javax.swing.JButton btnOderHistory;
    private javax.swing.JComboBox<String> companyNameList;
    private javax.swing.JLabel custName;
    private javax.swing.JLabel food1;
    private javax.swing.JLabel food2;
    private javax.swing.JLabel food3;
    private javax.swing.JLabel food4;
    private javax.swing.JLabel food5;
    private javax.swing.JLabel food6;
    private javax.swing.JLabel foodName1;
    private javax.swing.JLabel foodName2;
    private javax.swing.JLabel foodName3;
    private javax.swing.JLabel foodName4;
    private javax.swing.JLabel foodName5;
    private javax.swing.JLabel foodName6;
    private javax.swing.JPanel frame;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nextClick;
    // End of variables declaration//GEN-END:variables

    private void loadCompanyNames() {
        try{
            companyMap=CompanyDao.getAllCompanyIdAndName();
            Set<String> companyNames=companyMap.keySet();
            this.companyNameList.addItem("All");
            for(String companyName:companyNames){
                this.companyNameList.addItem(companyName);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "DB Error in CustomerRegisterFrame");
            ex.printStackTrace();
        }
    }

    private void showDetails() {
        ProductPojo p;
        if(listIndex<productList.size()){
            p=productList.get(listIndex);
            this.food1.setName(listIndex+"");
            this.food1.setText("");
            Image img=p.getProductImage();
            img=img.getScaledInstance(this.food1.getWidth(), this.food1.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            this.food1.setIcon(icon);
            this.foodName1.setText(p.getProductName());
            this.foodName1.setName(listIndex+"");
            listIndex++;
        }
        else{
            this.food1.setIcon(null);
            this.food1.setName(listIndex+"");
            this.food1.setText("N/A");
            this.foodName1.setText("N/A");
            this.foodName1.setName(listIndex+"");
            listIndex++;
            
        }
        if(listIndex<productList.size()){
            p=productList.get(listIndex);
            this.food2.setName(listIndex+"");
            this.food2.setText("");
            Image img=p.getProductImage();
            img=img.getScaledInstance(this.food2.getWidth(), this.food2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            this.food2.setIcon(icon);
            this.foodName2.setText(p.getProductName());
            this.foodName2.setName(listIndex+"");
            listIndex++;
        }
        else{
            this.food2.setIcon(null);
            this.food2.setName(listIndex+"");
            this.food2.setText("N/A");
            this.foodName2.setText("N/A");
            this.foodName2.setName(listIndex+"");
            listIndex++;
            
        }
        if(listIndex<productList.size()){
            p=productList.get(listIndex);
            this.food3.setName(listIndex+"");
            this.food3.setText("");
            Image img=p.getProductImage();
            img=img.getScaledInstance(this.food3.getWidth(), this.food3.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            this.food3.setIcon(icon);
            this.foodName3.setText(p.getProductName());
            this.foodName3.setName(listIndex+"");
            listIndex++;
        }
        else{
            this.food3.setIcon(null);
            this.food3.setName(listIndex+"");
            this.food3.setText("N/A");
            this.foodName3.setText("N/A");
            this.foodName3.setName(listIndex+"");
            listIndex++;
        }
        if(listIndex<productList.size()){
            p=productList.get(listIndex);
            this.food4.setName(listIndex+"");
            this.food4.setText("");
            Image img=p.getProductImage();
            img=img.getScaledInstance(this.food4.getWidth(), this.food4.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            this.food4.setIcon(icon);
            this.foodName4.setText(p.getProductName());
            this.foodName4.setName(listIndex+"");
            listIndex++;
        }
        else{
            this.food4.setIcon(null);
            this.food4.setName(listIndex+"");
            this.food4.setText("N/A");
            this.foodName4.setText("N/A");
            this.foodName4.setName(listIndex+"");
            listIndex++;
        }
        if(listIndex<productList.size()){
            p=productList.get(listIndex);
            this.food5.setName(listIndex+"");
            this.food5.setText("");
            Image img=p.getProductImage();
            img=img.getScaledInstance(this.food5.getWidth(), this.food5.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            this.food5.setIcon(icon);
            this.foodName5.setText(p.getProductName());
            this.foodName5.setName(listIndex+"");
            listIndex++;
        }
        else{
            this.food5.setIcon(null);
            this.food5.setName(listIndex+"");
            this.food5.setText("N/A");
            this.foodName5.setText("N/A");
            this.foodName5.setName(listIndex+"");
            listIndex++;
        }
        if(listIndex<productList.size()){
            p=productList.get(listIndex);
            this.food6.setName(listIndex+"");
            this.food6.setText("");
            Image img=p.getProductImage();
            img=img.getScaledInstance(this.food6.getWidth(), this.food6.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            this.food6.setIcon(icon);
            this.foodName6.setText(p.getProductName());
            this.foodName6.setName(listIndex+"");
            listIndex++;
        }
        else{
            this.food6.setIcon(null);
            this.food6.setName(listIndex+"");
            this.food6.setText("N/A");
            this.foodName6.setText("N/A");
            this.foodName6.setName(listIndex+"");
            listIndex++;
        }
    }
}
